//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiranV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Tbl
    {
        public Candidate_Tbl()
        {
            this.Skills_Tbl = new HashSet<Skills_Tbl>();
        }

        public int CandidateID { get; private set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int EmployeeID { get; set; }
        public string EmailID { get; set; }
        public string Psword { get; set; }
        public string ConfirmPsword { get; set; }
        public string AvatarUrl { get; set; }
    
        public virtual ICollection<Skills_Tbl> Skills_Tbl { get; set; }
    }
}
