//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiranV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Tbl
    {
        public Category_Tbl()
        {
            this.Skills_Tbl = new HashSet<Skills_Tbl>();
        }

        public int CategoryID { get; private set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Skills_Tbl> Skills_Tbl { get; set; }
    }
}
