//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiranV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills_Tbl
    {
        public Skills_Tbl()
        {
            this.Candidate_Tbl = new HashSet<Candidate_Tbl>();
            this.Category_Tbl = new HashSet<Category_Tbl>();
        }
    
        public int SkillID { get; private set; }
        public string SkillName { get; set; }
    
        public virtual ICollection<Candidate_Tbl> Candidate_Tbl { get; set; }
        public virtual ICollection<Category_Tbl> Category_Tbl { get; set; }
    }
}
